[project]
name = "kexp-data-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
